# Generated by Django 3.1.5 on 2021-08-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Serial_no',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='products',
            name='Serial_no',
            field=models.CharField(max_length=16),
        ),
    ]
