# Generated by Django 3.1.5 on 2021-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0002_auto_20210818_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Metric',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='Metric',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='Serial_no',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
