# Generated by Django 3.1.5 on 2021-08-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Retail', '0003_auto_20210818_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Serial_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Retail.products'),
        ),
    ]
