# Generated by Django 3.1.5 on 2021-08-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Serial_no', models.CharField(max_length=16, unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('Metric', models.CharField(max_length=20, null=True)),
                ('Items', models.IntegerField()),
                ('Min_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Retailers',
            fields=[
                ('Store_id', models.AutoField(primary_key=True, serialize=False)),
                ('Store_name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=20, null=True)),
                ('Telephone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Processed', models.BooleanField(default=False)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='Invent_auto.products')),
                ('Quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quantity', to='Invent_auto.products')),
                ('Serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Serial', to='Invent_auto.products')),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Store', to='Invent_auto.retailers')),
                ('located', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='located', to='Invent_auto.retailers')),
            ],
        ),
    ]
