# Generated by Django 3.2.6 on 2021-08-20 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invent_auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Store',
            field=models.ForeignKey(default='Store_id', on_delete=django.db.models.deletion.CASCADE, related_name='Retailer', to='Invent_auto.retailers'),
            preserve_default=False,
        ),
    ]
