# Generated by Django 3.2.6 on 2021-08-20 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invent_auto', '0002_products_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Store',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='Retailer', to='Invent_auto.retailers'),
        ),
    ]
