# Generated by Django 3.2.6 on 2021-08-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invent_auto', '0004_remove_products_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='Processed',
            new_name='processed',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='retailers',
            old_name='Store_id',
            new_name='store_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Quantity',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Serial',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Store',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Items',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Metric',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Min_no',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Serial_no',
        ),
        migrations.RemoveField(
            model_name='retailers',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='retailers',
            name='Location',
        ),
        migrations.RemoveField(
            model_name='retailers',
            name='Store_name',
        ),
        migrations.RemoveField(
            model_name='retailers',
            name='Telephone',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(default='maize', on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Invent_auto.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='Invent_auto.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='serial',
            field=models.ForeignKey(default='1122334455', on_delete=django.db.models.deletion.CASCADE, related_name='serial', to='Invent_auto.products'),
        ),
        migrations.AddField(
            model_name='orders',
            name='store_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='store', to='Invent_auto.retailers'),
        ),
        migrations.AddField(
            model_name='products',
            name='items',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='products',
            name='metric',
            field=models.CharField(default='2Kgs', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='min_no',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='Maize', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='serial_no',
            field=models.CharField(default='1122334455', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='retailers',
            name='contact',
            field=models.CharField(default='Wanjiru', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='retailers',
            name='location',
            field=models.CharField(default='Kayole', max_length=100),
        ),
        migrations.AddField(
            model_name='retailers',
            name='store_name',
            field=models.CharField(default='KEFIS', max_length=100),
        ),
        migrations.AddField(
            model_name='retailers',
            name='telephone',
            field=models.CharField(default='0707....', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='located',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='located', to='Invent_auto.retailers'),
        ),
    ]
